"""The mood palette (情绪色卡台) generated by grade/make_palette.mjs with chroma.js.

Colours are looked up by semantic role ("minister.robe") or token ("vermilion.6").  They come back
as `Swatch` tuples that remember their family and position on that family's ramp, so shading
moves along the same ramp instead of scaling RGB, which keeps every shade inside the palette.
"""
import json
import os
from functools import lru_cache
from pathlib import Path

PATH = Path(os.environ.get("LLM2VIDEO_PALETTE", Path(__file__).with_name("palette.json")))
DATA = json.loads(PATH.read_text(encoding="utf-8"))
ROLES = DATA["roles"]
FAMILIES = DATA["families"]
N_FINE = len(next(iter(FAMILIES.values()))["fine"])
N_STEPS = len(DATA["ladder"])
MIX_SPACE = DATA.get("mix", "oklab")  # space used for runtime blends: "oklab" or CIE "lab"


def _hex(s):
    s = s.lstrip("#")
    return int(s[0:2], 16), int(s[2:4], 16), int(s[4:6], 16)


# ----------------------------------------------------------------------------- OKLab (Ottosson)

def _lin(c):
    c /= 255.0
    return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4


def _gam(c):
    c = max(0.0, min(1.0, c))
    return 255.0 * (12.92 * c if c <= 0.0031308 else 1.055 * c ** (1 / 2.4) - 0.055)


@lru_cache(maxsize=65536)
def to_oklab(rgb):
    r, g, b = (_lin(float(v)) for v in rgb[:3])
    l = (0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b) ** (1 / 3)
    m = (0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b) ** (1 / 3)
    s = (0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b) ** (1 / 3)
    return (0.2104542553 * l + 0.7936177850 * m - 0.0040720468 * s,
            1.9779984951 * l - 2.4285922050 * m + 0.4505937099 * s,
            0.0259040371 * l + 0.7827717662 * m - 0.8086757660 * s)


def from_oklab(lab):
    L, a, b = lab
    l = (L + 0.3963377774 * a + 0.2158037573 * b) ** 3
    m = (L - 0.1055613458 * a - 0.0638541728 * b) ** 3
    s = (L - 0.0894841775 * a - 1.2914855480 * b) ** 3
    r = 4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s
    g = -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s
    bb = -0.0041960863 * l - 0.7034186147 * m + 1.7076147010 * s
    return tuple(int(round(_gam(v))) for v in (r, g, bb))


# CIE Lab (D65), for palettes generated with --space=lab / lch
_WHITE = (0.95047, 1.0, 1.08883)


def _f(t):
    return t ** (1 / 3) if t > 216 / 24389 else (24389 / 27 * t + 16) / 116


def _finv(t):
    return t ** 3 if t ** 3 > 216 / 24389 else (116 * t - 16) / (24389 / 27)


@lru_cache(maxsize=65536)
def to_lab(rgb):
    r, g, b = (_lin(float(v)) for v in rgb[:3])
    x = (0.4124564 * r + 0.3575761 * g + 0.1804375 * b) / _WHITE[0]
    y = (0.2126729 * r + 0.7151522 * g + 0.0721750 * b) / _WHITE[1]
    z = (0.0193339 * r + 0.1191920 * g + 0.9503041 * b) / _WHITE[2]
    fx, fy, fz = _f(x), _f(y), _f(z)
    # scaled to 0..1 lightness so callers can treat it like OKLab
    return ((116 * fy - 16) / 100, 5 * (fx - fy), 2 * (fy - fz))


def from_lab(lab):
    L, a, b = lab[0] * 100, lab[1] * 100, lab[2] * 100
    fy = (L + 16) / 116
    x, y, z = _finv(fy + a / 500) * _WHITE[0], _finv(fy) * _WHITE[1], _finv(fy - b / 200) * _WHITE[2]
    r = 3.2404542 * x - 1.5371385 * y - 0.4985314 * z
    g = -0.9692660 * x + 1.8760108 * y + 0.0415560 * z
    bb = 0.0556434 * x - 0.2040259 * y + 1.0572252 * z
    return tuple(int(round(_gam(v))) for v in (r, g, bb))


_TO, _FROM = (to_lab, from_lab) if MIX_SPACE == "lab" else (to_oklab, from_oklab)


# ----------------------------------------------------------------------------- swatches

class Swatch(tuple):
    """RGBA tuple that knows where it sits in the palette."""

    def __new__(cls, rgba, fam=None, pos=None):
        t = super().__new__(cls, rgba)
        t.fam, t.pos = fam, pos
        return t


@lru_cache(maxsize=None)
def _fine(fam):
    ramp = [_hex(h) for h in FAMILIES[fam]["fine"]]
    return ramp, [to_oklab(c)[0] for c in ramp]


def token(name):
    """Role or token -> (family, fine index)."""
    tok = ROLES.get(name, name)
    fam, step = tok.split(".", 1)  # steps may be fractional: "marble.2.5"
    return fam, int(round(float(step) * (N_FINE - 1) / (N_STEPS - 1)))


def pal(name, a=255):
    if name in DATA["special"]:
        return Swatch(_hex(DATA["special"][name]) + (a,))
    fam, i = token(name)
    return Swatch(_fine(fam)[0][i] + (a,), fam, i)


def at(fam, i, a=255):
    i = max(0, min(N_FINE - 1, int(round(i))))
    return Swatch(_fine(fam)[0][i] + (a,), fam, i)


def shade(c, k):
    """Darken (k<1) or lighten (k>1).  Palette colours slide along their own ramp."""
    alpha = tuple(c[3:])
    lab = to_oklab(tuple(c[:3]))
    target = lab[0] * k ** 0.7
    fam = getattr(c, "fam", None)
    if fam is not None:
        _, Ls = _fine(fam)
        # ramp lightness falls with index; pick the nearest fine step
        lo, hi = 0, N_FINE - 1
        while lo < hi:
            mid = (lo + hi) // 2
            if Ls[mid] > target:
                lo = mid + 1
            else:
                hi = mid
        i = lo if lo == 0 or abs(Ls[lo] - target) < abs(Ls[lo - 1] - target) else lo - 1
        return Swatch(_fine(fam)[0][i] + alpha, fam, i)
    # off-palette colour: scale lightness in the palette space and lean toward the mood light/shadow
    lab = _TO(tuple(c[:3]))
    target = lab[0] * k ** 0.7
    tint = _TO(_hex(DATA["mood"]["light" if k > 1 else "shadow"]))
    w = min(0.35, abs(1 - k) * 0.6)
    L = target
    a = lab[1] + (tint[1] - lab[1]) * w
    b = lab[2] + (tint[2] - lab[2]) * w
    return Swatch(_FROM((L, a, b)) + alpha)


def mix(c1, c2, t):
    """Perceptual blend in the palette's Lab space (keeps alpha of c1)."""
    x, y = _TO(tuple(c1[:3])), _TO(tuple(c2[:3]))
    lab = tuple(p + (q - p) * t for p, q in zip(x, y))
    return _FROM(lab) + tuple(c1[3:4])


def sky_stops():
    return [(e, _hex(h)) for e, h in DATA["sky"]]


def rgb(name):
    return tuple(pal(name)[:3])


def luminance_ratio(c1, c2):
    def Y(c):
        r, g, b = (_lin(float(v)) for v in c[:3])
        return 0.2126 * r + 0.7152 * g + 0.0722 * b
    a, b = sorted((Y(c1), Y(c2)), reverse=True)
    return (a + 0.05) / (b + 0.05)



